config/routes.rb
Rails.application.routes.draw do
  resources :athleteseries
  resources :series
  resources :discipline_championships
  resources :discipline_details
  resources :disciplines
  resources :referee_levels
  resources :referees
  resources :championships
  resources :regions
  resources :clubs
  resources :coaches
  resources :athletes
  devise_for :users
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
end

app/models/athleteserie.rb
class Athleteserie < ApplicationRecord
end

app/models/championship.rb
class Championship < ApplicationRecord
end

app/models/club.rb
class Club < ApplicationRecord
end

app/models/coach.rb
class Coach < ApplicationRecord
end

app/models/discipline.rb
class Discipline < ApplicationRecord
end

app/models/discipline_detail.rb
class DisciplineDetail < ApplicationRecord
end

app/models/referee.rb
class Referee < ApplicationRecord
end

app/models/referee_level.rb
class RefereeLevel < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/discipline_details_controller.rb
class DisciplineDetailsController < ApplicationController
  before_action :set_discipline_detail, only: [:show, :edit, :update, :destroy]

  # GET /discipline_details
  # GET /discipline_details.json
  def index
    @discipline_details = DisciplineDetail.all
  end

  # GET /discipline_details/1
  # GET /discipline_details/1.json
  def show
  end

  # GET /discipline_details/new
  def new
    @discipline_detail = DisciplineDetail.new
  end

  # GET /discipline_details/1/edit
  def edit
  end

  # POST /discipline_details
  # POST /discipline_details.json
  def create
    @discipline_detail = DisciplineDetail.new(discipline_detail_params)

    respond_to do |format|
      if @discipline_detail.save
        format.html { redirect_to @discipline_detail, notice: 'Discipline detail was successfully created.' }
        format.json { render :show, status: :created, location: @discipline_detail }
      else
        format.html { render :new }
        format.json { render json: @discipline_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discipline_details/1
  # PATCH/PUT /discipline_details/1.json
  def update
    respond_to do |format|
      if @discipline_detail.update(discipline_detail_params)
        format.html { redirect_to @discipline_detail, notice: 'Discipline detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline_detail }
      else
        format.html { render :edit }
        format.json { render json: @discipline_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discipline_details/1
  # DELETE /discipline_details/1.json
  def destroy
    @discipline_detail.destroy
    respond_to do |format|
      format.html { redirect_to discipline_details_url, notice: 'Discipline detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline_detail
      @discipline_detail = DisciplineDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_detail_params
      params.require(:discipline_detail).permit(:name, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/discipline_details_helper.rb
module DisciplineDetailsHelper
end

app/helpers/referees_helper.rb
module RefereesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/discipline_details/_form.html.erb
<%= form_with(model: discipline_detail, local: true) do |form| %>
  <% if discipline_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline_detail.errors.count, "error") %> prohibited this discipline_detail from being saved:</h2>

      <ul>
      <% discipline_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :discipline_detail_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :discipline_detail_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discipline_details/edit.html.erb
<h1>Editing Discipline Detail</h1>

<%= render 'form', discipline_detail: @discipline_detail %>

<%= link_to 'Show', @discipline_detail %> |
<%= link_to 'Back', discipline_details_path %>

app/views/discipline_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discipline Details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discipline_details.each do |discipline_detail| %>
      <tr>
        <td><%= discipline_detail.name %></td>
        <td><%= discipline_detail.value %></td>
        <td><%= link_to 'Show', discipline_detail %></td>
        <td><%= link_to 'Edit', edit_discipline_detail_path(discipline_detail) %></td>
        <td><%= link_to 'Destroy', discipline_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discipline Detail', new_discipline_detail_path %>

app/views/discipline_details/new.html.erb
<h1>New Discipline Detail</h1>

<%= render 'form', discipline_detail: @discipline_detail %>

<%= link_to 'Back', discipline_details_path %>

app/views/discipline_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @discipline_detail.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @discipline_detail.value %>
</p>

<%= link_to 'Edit', edit_discipline_detail_path(@discipline_detail) %> |
<%= link_to 'Back', discipline_details_path %>