config/routes.rb
Rails.application.routes.draw do
  resources :athleteseries
  resources :series
  resources :discipline_championships
  resources :discipline_details
  resources :disciplines
  resources :referee_levels
  resources :referees
  resources :championships
  resources :regions
  resources :clubs
  resources :coaches
  resources :athletes
  devise_for :users
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
end

app/models/athleteserie.rb
class Athleteserie < ApplicationRecord
end

app/models/championship.rb
class Championship < ApplicationRecord
end

app/models/club.rb
class Club < ApplicationRecord
end

app/models/coach.rb
class Coach < ApplicationRecord
end

app/models/discipline.rb
class Discipline < ApplicationRecord
end

app/models/discipline_detail.rb
class DisciplineDetail < ApplicationRecord
end

app/models/referee.rb
class Referee < ApplicationRecord
end

app/models/referee_level.rb
class RefereeLevel < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :set_championship, only: [:show, :edit, :update, :destroy]

  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
  end

  # GET /championships/new
  def new
    @championship = Championship.new
  end

  # GET /championships/1/edit
  def edit
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1
  # PATCH/PUT /championships/1.json
  def update
    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: 'Championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def championship_params
      params.require(:championship).permit(:name, :initdate, :findate, :idRegion, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/referees_helper.rb
module RefereesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/championships/_form.html.erb
<div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Nuevo Campeonato</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal">
              <div class="box-body">

            <%= simple_form_for @championship do |f| %>
            <% if championship.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(championship.errors.count, "error") %> Error al guardar:</h2>

                  <ul>
                  <% championship.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
             <div class="form-group">
             <label for="text" class="col-sm-1 control-label"></label>
             <div class="col-sm-10">
              <%= f.input :name , placeholder:'Nombre del campeonato', required: true, error:'El campo nombre es obligatorio', label: false %>
             </div>
             </div>
              <div class="form-group">
             <label for="text" class="col-sm-1 control-label"></label>
             <div class="col-sm-10">
              <%= f.input :initdate , placeholder:'Fecha de inicio', required: true, error:'El campo fecha de inicio es obligatorio', label: false %>
             </div>
             </div>
              <div class="form-group">
             <label for="text" class="col-sm-1 control-label"></label>
             <div class="col-sm-10">
              <%= f.input :findate , placeholder:'Fecha de término', required: true, error:'El campo fecha de término es obligatorio', label: false %>
             </div>
             </div>
              <div class="form-group">
             <label for="text" class="col-sm-1 control-label"></label>
             <div class="col-sm-10">
              <%= f.input :address , placeholder:'Dirección', required: true, error:'El campo dirección es obligatorio', label: false %>
             </div>
             </div>
               <div class="form-group">
             <label for="text" class="col-sm-1 control-label"></label>
             <div class="col-sm-10">
              <%= f.input :idRegion , placeholder:'Región', required: true, error:'El campo nombre de región es obligatorio', label: false %>
             </div>
             </div>
             <!-- /.box-body -->
              <div class="box-footer">
                    <%= link_to "Cancelar", championships_path , class: "btn btn-warning"%>              
                    <%= f.button :submit, class: "btn btn-info pull-right"%>
            <% end %>
                           </div>
              <!-- /.box-footer -->
            </form>
          </div>

app/views/championships/edit.html.erb
<h1>Editing Championship</h1>

<%= render 'form', championship: @championship %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Championships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initdate</th>
      <th>Findate</th>
      <th>Idregion</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @championships.each do |championship| %>
      <tr>
        <td><%= championship.name %></td>
        <td><%= championship.initdate %></td>
        <td><%= championship.findate %></td>
        <td><%= championship.idRegion %></td>
        <td><%= championship.address %></td>
        <td><%= link_to 'Show', championship %></td>
        <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
        <td><%= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<%= render 'form', championship: @championship %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @championship.name %>
</p>

<p>
  <strong>Initdate:</strong>
  <%= @championship.initdate %>
</p>

<p>
  <strong>Findate:</strong>
  <%= @championship.findate %>
</p>

<p>
  <strong>Idregion:</strong>
  <%= @championship.idRegion %>
</p>

<p>
  <strong>Address:</strong>
  <%= @championship.address %>
</p>

<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>