config/routes.rb
Rails.application.routes.draw do
  resources :athleteseries
  resources :series
  resources :discipline_championships
  resources :discipline_details
  resources :disciplines
  resources :referee_levels
  resources :referees
  resources :championships
  resources :regions
  resources :clubs
  resources :coaches
  resources :athletes
  devise_for :users
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
end

app/models/athleteserie.rb
class Athleteserie < ApplicationRecord
end

app/models/championship.rb
class Championship < ApplicationRecord
end

app/models/club.rb
class Club < ApplicationRecord
end

app/models/coach.rb
class Coach < ApplicationRecord
end

app/models/discipline.rb
class Discipline < ApplicationRecord
end

app/models/discipline_detail.rb
class DisciplineDetail < ApplicationRecord
end

app/models/referee.rb
class Referee < ApplicationRecord
end

app/models/referee_level.rb
class RefereeLevel < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Serie.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Serie.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Serie was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:idDisciplineChampionship, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/referees_helper.rb
module RefereesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idDisciplineChampionship %>
    <%= form.text_field :idDisciplineChampionship, id: :series_idDisciplineChampionship %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :series_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Iddisciplinechampionship</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.idDisciplineChampionship %></td>
        <td><%= series.name %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iddisciplinechampionship:</strong>
  <%= @series.idDisciplineChampionship %>
</p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_path %>